name: Run plugin tests

on:
  pull_request:
    branches: [main]
    paths:
      - src/**
      - test/**
      - package.json
      - package-lock.json
  workflow_dispatch:
    # manually triggered

# Required for test results reporting.
permissions:
  checks: write
  pull-requests: write

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run test
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit Test Results
          files: |
            unit.xml
          time_unit: seconds
      - run: npm run test:integration
        env:
          JIRA_TOKEN_CLOUD: ${{ secrets.JIRA_TOKEN_CLOUD }}
          JIRA_PASSWORD_SERVER: ${{ secrets.JIRA_PASSWORD_SERVER }}
          JIRA_USERNAME_CLOUD: ${{ secrets.JIRA_USERNAME_CLOUD }}
          JIRA_USERNAME_SERVER: ${{ secrets.JIRA_USERNAME_SERVER }}
          XRAY_CLIENT_ID_CLOUD: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET_CLOUD: ${{ secrets.XRAY_CLIENT_SECRET }}
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Integration Test Results
          files: |
            integration.xml
          time_unit: seconds
